version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./postgres_instance/data:/var/lib/postgresql/data