"""Initial migration

Revision ID: 83d50d243053
Revises: 
Create Date: 2024-01-16 01:14:59.920434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d50d243053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('ban_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='awesome_chat'
    )
    op.create_table('message_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('reset_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['awesome_chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='awesome_chat'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['awesome_chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='awesome_chat'
    )
    op.create_table('user_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=True),
    sa.Column('offender_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complainant_id'], ['awesome_chat.users.id'], ),
    sa.ForeignKeyConstraint(['offender_id'], ['awesome_chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='awesome_chat'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['awesome_chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='awesome_chat'
    )
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['awesome_chat.messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['awesome_chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='awesome_chat'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_messages', schema='awesome_chat')
    op.drop_table('user_sessions', schema='awesome_chat')
    op.drop_table('user_complaints', schema='awesome_chat')
    op.drop_table('messages', schema='awesome_chat')
    op.drop_table('message_limits', schema='awesome_chat')
    op.drop_table('users', schema='awesome_chat')
    # ### end Alembic commands ###
